from . import lab_test_units
from . import lab_test_type
from . import disease_names
from . import disease_main_category
from . import disease_sub_category
from . import patients
from . import genetic_risks
from . import medical_specialities
from . import blood_groups
from . import patient_disease
from . import occupation
from . import patient_info
from . import medicament_category
from . import medicament_form
from . import medicament_admin_routes
from . import medicament_dose_units
from . import medicament_dosage_frequency
from . import medicaments
from . import patient_medicament
from . import physician_info
from . import patient_medicament_indication
from . import institution
from . import speciality
from . import appointments
from . import patient_status
from . import patient_urgency_level
from . import appointment_status
from . import disease_severity
from . import disease_status
from . import disease_allergy
from . import lab_test_request
# from . import lab_invoice
from . import prescriptions